version: '3.9'

services:
  db:
    image: mysql:8.1
    container_name: portal-noticias-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: bossaws2024/portal-noticias-be:latest
    container_name: portal-noticias-backend
    restart: unless-stopped
    expose:
      - "${SERVER_PORT}"  # expõe apenas internamente para o Nginx
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: portal-noticias-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    container_name: portal-noticias-certbot
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done;'"
    depends_on:
      - nginx

volumes:
  db_data:
